### ISSUE TITLE
how to test same on test dataset

### ISSUE THREAD

**Issue by shubhaminnani** [nv-tlabs/GSCNN#12]
@tovacinni @ShreyasSkandanS  @varunjampani @davidjesusacu  Hi, I have a question what if i want to predict i.e. test the test data? how can we do it?
Thanks in advance.

while evaluting on other data its shows error while evaluting any suggestions to remove it?
Error - `Sizes of tensors must match except in dimension 0. Got 720 and 1080 in dimension 2`

**Comment by tovacinni** [comment]
@shubhaminnani 

Thanks for your interest in our work, and also sorry for the belated reply. I've been extremely busy lately. :(

Regarding your second issue, it's likely because you did not implement the data loader correctly. You need to make sure that the spacial resolution of your input needs to match up in order to concatenate the dataset into batches.

If you want to predict with the test data, you should be able to do so by modifying the code such that it loads the test set instead, and output the inferred images to a desired folder of choice. Our released code currently does not officially support this by default, but should be a quick change. In a future version, we can support this if there is enough demand (likely will be later when I have more time!)
